services:
  - type: web
    name: loja-api
    runtime: docker
    rootDir: .
    buildCommand: "./mvnw clean install -DskipTests"
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: spring.datasource.url
        value: '{{ env.DATABASE_URL }}'
      - key: spring.datasource.username
        value: '{{ env.DATABASE_USER }}'
      - key: spring.datasource.password
        value: '{{ env.DATABASE_PASSWORD }}'
